<?php
    global $session;
    global $DBInstance;
?>

<div class="col-md-6 tndr-reg-form">
    <div id="public-reg" class="region region-content">
        <div id="public_news_alert" class="message"><?php if(!empty($session->message)){ echo output_message($session->message); } ?></div>
        <div id="termsandconditions" name="tbcreg_form" action="./op/actiontndrr.php?pg=1" method="POST" class="form-control form-signin">
            <h5>1. Terms</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>2. Use License - Templates</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>3. Use License - articles</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>4. Intellectual Property</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>5. Disclaimer</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>6. Limitations</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>7. Accuracy of materials</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>8. Links</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>9. Modifications</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>10. Governing Law</h5>
            <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p>
            <h5>Version 1.1 - Effective date: November 1, 2017.</h5>
            <!-- <p class="justify-content flex-column">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, fugit cum, laboriosam excepturi voluptatibus illo beatae magnam impedit, ipsam delectus temporibus repudiandae. Incidunt amet reiciendis doloremque aspernatur soluta adipisci nihil. Cumque odio quaerat sed ipsa. Corrupti quia culpa vero amet corporis nihil, ipsum officia. Tempore quo asperiores doloremque voluptas! Asperiores, modi beatae doloribus, in voluptatum saepe ad dolore cumque non nostrum temporibus hic aspernatur tempore laudantium omnis veniam expedita ducimus ut. Autem officiis molestiae alias excepturi voluptates non minima optio soluta nulla nostrum error possimus, voluptatibus similique natus, illo mollitia est exercitationem illum commodi quasi obcaecati? Neque exercitationem excepturi laborum.</p> -->
            <p>
            </p> 
        </div>
    </div>
</div>